### ISSUE TITLE
What happens if the user enters a blank line twice?

### ISSUE THREAD

**Issue by anthonycarlos** [liliverson45/Hello_World#1]
The program executes linearly from top to botton. Can you find a way to handle multiple blank lines?

**Comment by liliverson45** [comment]
Currently I have it the error handling to not accept blanks at all. It will give you the message "I'm sorry, this field cannot be blank." Then repeat the question you were currently on. I also have it set to strip any spaces. For example, if you added 10 blank spaces then typed a name, on the output the spaces will have been stripped and your input would appear.

**Comment by anthonycarlos** [comment]
John:

You're absolutely right. I actually ran it and saw exactly what you described. Are you ready to move on to something else? Here's a new programming assignment:

"Write a program that prints the numbers from 1 to 100. But for multiples of three print “Fizz” instead of the number and for the multiples of five print “Buzz”. For numbers which are multiples of both three and five print “FizzBuzz”."

Are you up to it?

Thanks,

-Anthony
