### ISSUE TITLE
Duplication of index values

### ISSUE THREAD

**Issue by anthonycarlos** [liliverson45/Hello_World#2]
Here's the output for the first 15 numbers. There is duplication of numbers. Also, should we start at 1?

Hello, I am printing to 100
0
FizzBuzz
1
1
2
2
3
Fizz
4
4
5
Buzz
6
Fizz
7
7
8
8
9
Fizz
10
Buzz
11
11
12
Fizz
13
13
14
14
15
FizzBuzz

**Comment by liliverson45** [comment]
Hi Anthony. I found my issue. Simply commenting out the first #puts i fixed the issue. I will starting working on the next objective. I have ran it again with the following results"
Hello, I am printing to 100
FizzBuzz
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
